
Person1Dialog = [];
 
    Person1Day1Dia = [];
      Person1Day1Dia1 = [];
      Person1Day1Dia1.push("Hey there, looks Like you're up.");
      Person1Day1Dia1.push("It seems that we're all locked ");
      Person1Day1Dia1.push("in this room. The only thing here");
      Person1Day1Dia1.push("besides some windows that we have to ");
      Person1Day1Dia1.push("go by is the note on the table there.");
      Person1Day1Dia2 = [];
      Person1Day1Dia2.push("No clue where we're at buddy.");
      Person1Day1Dia2.push("We can see through the windows but");
      Person1Day1Dia2.push("It's just a bunch of farmland with");
      Person1Day1Dia2.push("no road in sight. Looks like we're");
      Person1Day1Dia2.push("not gonna get much help.");
      Person1Day1Dia3 = [];
      Person1Day1Dia3.push("Woah there! I didn't do anything like");
      Person1Day1Dia3.push("that, I just woke up first that's all.");
      Person1Day1Dia3.push("You got put out by a rag moist from");
      Person1Day1Dia3.push("Desflurane right?");
      Person1Day1Dia = [];
      Person1Day1Dia.push(Person1Day1Dia1);
      Person1Day1Dia.push(Person1Day1Dia2);
      Person1Day1Dia.push(Person1Day1Dia3);
  Person1Dialog.push(Person1Day1Dia);
      Person1Day2Dia1 = [];
      Person1Day2Dia1.push("Find anything New?");
      Person1Day2Dia2 = [];
      Person1Day2Dia2.push("Damn, are we ever going to get out?");
      Person1Day2Dia3 = [];
      Person1Day2Dia3.push("Oh um.... I'm a chemist, Desflurane");
      Person1Day2Dia3.push("is a much easier chemical to get.");
      Person1Day2Dia3.push("Chlorophorm makes sense but it's");
      Person1Day2Dia3.push("not as fast acting as Desflurane.");
      Person1Day2Dia = [];
      Person1Day2Dia.push(Person1Day2Dia1);
      Person1Day2Dia.push(Person1Day2Dia2);
      Person1Day2Dia.push(Person1Day2Dia3);
  Person1Dialog.push(Person1Day2Dia);
      Person1Day3Dia1 = [];
      Person1Day3Dia1.push("Hey bud, Please tell me you found");
      Person1Day3Dia1.push("Something new, any of us could be");
      Person1Day3Dia1.push("next.");
      Person1Day3Dia2 = [];
      Person1Day3Dia2.push("I think the next guy is the murderer");
      Person1Day3Dia2.push("He's just rubs me the wrong way.");
      Person1Day3Dia3 = [];
      Person1Day3Dia3.push("Wait, I really didn't do it.");
      Person1Day3Dia3.push("Please don't kill me before night.");
      Person1Day3Dia = [];
      Person1Day3Dia.push(Person1Day3Dia1);
      Person1Day3Dia.push(Person1Day3Dia2);
      Person1Day3Dia.push(Person1Day3Dia3);
  Person1Dialog.push(Person1Day3Dia);
Person2Dialog = [];
 Person2Day1Dia1=[];
      Person2Day1Dia1.push("Where are we! Who are You!");
      Person2Day1Dia2 = [];
      Person2Day1Dia2.push("I JUST WANT TO GO HOME!");
      Person2Day1Dia3 = [];
      Person2Day1Dia3.push("LEAVE ME ALONE!!!");
      Person2Day1Dia = [];
      Person2Day1Dia.push(Person2Day1Dia1);
      Person2Day1Dia.push(Person2Day1Dia2);
      Person2Day1Dia.push(Person2Day1Dia3);
  Person2Dialog.push(Person2Day1Dia);
      Person2Day2Dia1 = [];
      Person2Day2Dia1.push("*Crying* I just wanna go home...");
      Person2Day2Dia1.push("I just wanna go home. I just wanna go home.");
      Person2Day2Dia1.push("I just wanna go home......");
      Person2Day2Dia2 = [];
      Person2Day2Dia2.push("Thanks for calming me down.");
      Person2Day2Dia3 = [];
      Person2Day2Dia3.push("*Scream* AHHHHHHHHHHHHHH");
      Person2Day2Dia = [];
      Person2Day2Dia.push(Person2Day2Dia1);
      Person2Day2Dia.push(Person2Day2Dia2);
      Person2Day2Dia.push(Person2Day2Dia3);
  Person2Dialog.push(Person2Day2Dia);
      Person2Day3Dia1 = [];
      Person2Day3Dia1.push("*Silence*");
      Person2Day3Dia2 = [];
      Person2Day3Dia2.push("Thanks...I guess.");
      Person2Day3Dia3 = [];
      Person2Day3Dia3.push("*Curls up into ball*");
      Person2Day3Dia = [];
      Person2Day3Dia.push(Person2Day3Dia1);
      Person2Day3Dia.push(Person2Day3Dia2);
      Person2Day3Dia.push(Person2Day3Dia3);
  Person2Dialog.push(Person2Day3Dia);
Person3Dialog = [];
      Person3Day1Dia1 = [];
      Person3Day1Dia1.push("Who the heck are you?");
      Person3Day1Dia2 = [];
      Person3Day1Dia2.push("Why should I listen to you?");
      Person3Day1Dia3 = [];
      Person3Day1Dia3.push("Screw off bub!");
      Person3Day1Dia = [];
      Person3Day1Dia.push(Person3Day1Dia1);
      Person3Day1Dia.push(Person3Day1Dia2);
      Person3Day1Dia.push(Person3Day1Dia3);
  Person3Dialog.push(Person3Day1Dia);
      Person3Day2Dia1 = [];
      Person3Day2Dia1.push("*Whisper* Hey who do you think the");
      Person3Day2Dia1.push("murder is?");
      Person3Day2Dia2 = [];
      Person3Day2Dia2.push("Thanks for nothing dumbasss.");
      Person3Day2Dia3 = [];
      Person3Day2Dia3.push("You Spread that nonsense I\'ll");
      Person3Day2Dia3.push("kill your scrawny ass.");
      Person3Day2Dia = [];
      Person3Day2Dia.push(Person3Day2Dia1);
      Person3Day2Dia.push(Person3Day2Dia2);
      Person3Day2Dia.push(Person3Day2Dia3);
  Person3Dialog.push(Person3Day2Dia);
      Person3Day3Dia1 = [];
      Person3Day3Dia1.push("If the killer comes my way");
      Person3Day3Dia1.push("I\'ll clobber him!");
      Person3Day3Dia2 = [];
      Person3Day3Dia2.push("Thanks, You better hope you\'re");
      Person3Day3Dia2.push("not the killer.");
      Person3Day3Dia3 = [];
      Person3Day3Dia3.push("Of course I can f*cking take him");
      Person3Day3Dia = [];
      Person3Day3Dia.push(Person3Day3Dia1);
      Person3Day3Dia.push(Person3Day3Dia2);
      Person3Day3Dia.push(Person3Day3Dia3);
  Person3Dialog.push(Person3Day3Dia);
Person4Dialog = [];
      Person4Day1Dia1 = [];
      Person4Day1Dia1.push("I could use some pancakes...");
      Person4Day1Dia2 = [];
      Person4Day1Dia2.push("OF COURSE I LIKE PANCAKES!!!");
      Person4Day1Dia3 = [];
      Person4Day1Dia3.push("It\'s always the time for pancakes!!!");
      Person4Day1Dia = [];
      Person4Day1Dia.push(Person4Day1Dia1);
      Person4Day1Dia.push(Person4Day1Dia2);
      Person4Day1Dia.push(Person4Day1Dia3);
  Person4Dialog.push(Person4Day1Dia);
      Person4Day2Dia1 = [];
      Person4Day2Dia1.push("Find us some pancakes yet?");
      Person4Day2Dia2 = [];
      Person4Day2Dia2.push("*Eyes tear up* I won\'t give up hope");
      Person4Day2Dia3 = [];
      Person4Day2Dia3.push("So what? pancakes still taste good");
      Person4Day2Dia = [];
      Person4Day2Dia.push(Person4Day2Dia1);
      Person4Day2Dia.push(Person4Day2Dia2);
      Person4Day2Dia.push(Person4Day2Dia3);
  Person4Dialog.push(Person4Day2Dia);
      Person4Day3Dia1 = [];
      Person4Day3Dia1.push("I don't think, I\'m gonna find pancakes.");
      Person4Day3Dia2 = [];
      Person4Day3Dia2.push("That\'s right! Never Give In!!!");
      Person4Day3Dia3 = [];
      Person4Day3Dia3.push("*Cries* I\'m fine with death but not");
      Person4Day3Dia3.push("never again eating pancakes!!!");
      Person4Day3Dia = [];
      Person4Day3Dia.push(Person4Day3Dia1);
      Person4Day3Dia.push(Person4Day3Dia2);
      Person4Day3Dia.push(Person4Day3Dia3);
  Person4Dialog.push(Person4Day3Dia);
Person5Dialog = [];
      Person5Day1Dia1 = [];
      Person5Day1Dia1.push("*Silence* ....");
      Person5Day1Dia2 = [];
      Person5Day1Dia2.push("*Silence* ....");
      Person5Day1Dia3 = [];
      Person5Day1Dia3.push("*Stares with Anger* ....");
      Person5Day1Dia = [];
      Person5Day1Dia.push(Person5Day1Dia1);
      Person5Day1Dia.push(Person5Day1Dia2);
      Person5Day1Dia.push(Person5Day1Dia3);
  Person5Dialog.push(Person5Day1Dia);
      Person5Day2Dia1 = [];
      Person5Day2Dia1.push("*Silence* ....");
      Person5Day2Dia2 = [];
      Person5Day2Dia2.push("*Silence* ....");
      Person5Day2Dia3 = [];
      Person5Day2Dia3.push("*Stares with Anger* ....");
      Person5Day2Dia = [];
      Person5Day2Dia.push(Person5Day2Dia1);
      Person5Day2Dia.push(Person5Day2Dia2);
      Person5Day2Dia.push(Person5Day2Dia3);
  Person5Dialog.push(Person5Day2Dia);
  Person5Day3Dia1 = [];
      Person5Day3Dia1.push("*Silence* ....");
      Person5Day3Dia2 = [];
      Person5Day3Dia2.push("*Silence* ....");
      Person5Day3Dia3 = [];
      Person5Day3Dia3.push("*Stares with Anger* ....");
      Person5Day3Dia = [];
      Person5Day3Dia.push(Person5Day3Dia1);
      Person5Day3Dia.push(Person5Day3Dia2);
      Person5Day3Dia.push(Person5Day3Dia3);
  Person5Dialog.push(Person5Day3Dia);
Person6Dialog = [];
    Person6Day1Dia1 = [];
      Person6Day1Dia1.push("Can I help you with something?");
      Person6Day1Dia1.push("Oh right! The letter right?");
      Person6Day1Dia1.push("It basically says that we won't get");
      Person6Day1Dia1.push("out, at least not alive. It says that");
      Person6Day1Dia1.push("there is a killer somewhere in this");
      Person6Day1Dia1.push("room.");
      Person6Day1Dia2 = [];
      Person6Day1Dia2.push("It also says that every night we need");
      Person6Day1Dia2.push("to kill someone or all of us will die");
      Person6Day1Dia2.push("and that when we sleep the killer");
      Person6Day1Dia2.push("will kill another. The only way out");
      Person6Day1Dia2.push("is to kill the killer");
      Person6Day1Dia3 = [];
      Person6Day1Dia3.push("It also says that every night we need");
      Person6Day1Dia3.push("to kill someone or all of us will die");
      Person6Day1Dia3.push("and that when we sleep the killer");
      Person6Day1Dia3.push("will kill another. The only way out");
      Person6Day1Dia3.push("is to kill the killer");
      Person6Day1Dia = [];
      Person6Day1Dia.push(Person6Day1Dia1);
      Person6Day1Dia.push(Person6Day1Dia2);
      Person6Day1Dia.push(Person6Day1Dia3);
  Person6Dialog.push(Person6Day1Dia);
      Person6Day2Dia1 = [];
      Person6Day2Dia1.push("So did you get knocked out by");
      Person6Day2Dia1.push("chloroform as well?");
      Person6Day2Dia2 = [];
      Person6Day2Dia2.push("Really he said it wasn't chloroform?");
      Person6Day2Dia2.push("Normally kidnappers use chloroform right?");
      Person6Day2Dia3 = [];
      Person6Day2Dia3.push("I haven't found anything else weird");
      Person6Day2Dia3.push("with the note.");
      Person6Day2Dia = [];
      Person6Day2Dia.push(Person6Day2Dia1);
      Person6Day2Dia.push(Person6Day2Dia2);
      Person6Day2Dia.push(Person6Day2Dia3);
  Person6Dialog.push(Person6Day2Dia);
  Person6Day3Dia1 = [];
      Person6Day3Dia1.push("I hope your not voting for me.");
      Person6Day3Dia2 = [];
      Person6Day3Dia2.push("Well I shouldn't have anything to worry");
      Person6Day3Dia2.push("about, or do I?");
      Person6Day3Dia3 = [];
      Person6Day3Dia3.push("Why do you think I'm hiding something?");
      Person6Day3Dia = [];
      Person6Day3Dia.push(Person6Day3Dia1);
      Person6Day3Dia.push(Person6Day3Dia2);
      Person6Day3Dia.push(Person6Day3Dia3);
  Person6Dialog.push(Person6Day3Dia);
  
  
    // User Questions
    
  DialogueChoices = [];
    DialoguePerson1 = [];
      DialogueChoicesP1D1 = [];
        DialogueChoicesP1D1.push("Where are we?");
        DialogueChoicesP1D1.push("Did you abduct me?");
      DialogueChoicesP1D2 = [];
        DialogueChoicesP1D2.push("Nah");
        DialogueChoicesP1D2.push("I found a bottle labled Desfulrane");
      DialogueChoicesP1D3 = [];
        DialogueChoicesP1D3.push("No do you have any suspects?");
        DialogueChoicesP1D3.push("I think you did it.");
      DialoguePerson1.push(DialogueChoicesP1D1);
      DialoguePerson1.push(DialogueChoicesP1D2);
      DialoguePerson1.push(DialogueChoicesP1D3);
    DialoguePerson2 = [];
      DialogueChoicesP2D1 = [];
        DialogueChoicesP2D1.push("I\'m your friend");
        DialogueChoicesP2D1.push("I\'m stuck here just like you.");
      DialogueChoicesP2D2 = [];
        DialogueChoicesP2D2.push("It\'s to early to freak out.");
        DialogueChoicesP2D2.push("I don\'t think we\'re going home.");
      DialogueChoicesP2D3 = [];
        DialogueChoicesP2D3.push("Don\'t worry we\'ll make it.");
        DialogueChoicesP2D3.push("You\'re probably next.");
      DialoguePerson2.push(DialogueChoicesP2D1);
      DialoguePerson2.push(DialogueChoicesP2D2);
      DialoguePerson2.push(DialogueChoicesP2D3);
    DialoguePerson3 = [];
      DialogueChoicesP3D1 = [];
        DialogueChoicesP3D1.push("The guy in charge.");
        DialogueChoicesP3D1.push("Someone smart.");
      DialogueChoicesP3D2 = [];
        DialogueChoicesP3D2.push("No clue.");
        DialogueChoicesP3D2.push("I think you\'re the killer.");
      DialogueChoicesP3D3 = [];
        DialogueChoicesP3D3.push("Looks like you can handle him.");
        DialogueChoicesP3D3.push("You sure you can take him?");
      DialoguePerson3.push(DialogueChoicesP3D1);
      DialoguePerson3.push(DialogueChoicesP3D2);
      DialoguePerson3.push(DialogueChoicesP3D3);
    DialoguePerson4 = [];
      DialogueChoicesP4D1 = [];
        DialogueChoicesP4D1.push("Do you like pancakes?");
        DialogueChoicesP4D1.push("I don\'t think now's the time..");
      DialogueChoicesP4D2 = [];
        DialogueChoicesP4D2.push("No, Sorry.");
        DialogueChoicesP4D2.push("This is serious.");
      DialogueChoicesP4D3 = [];
        DialogueChoicesP4D3.push("We\'ll find you pancakes.");
        DialogueChoicesP4D3.push("I can't find any pancakes.");
      DialoguePerson4.push(DialogueChoicesP4D1);
      DialoguePerson4.push(DialogueChoicesP4D2);
      DialoguePerson4.push(DialogueChoicesP4D3);
    DialoguePerson5 = [];
      DialogueChoicesP5D1 = [];
        DialogueChoicesP5D1.push("Nice to meet you.");
        DialogueChoicesP5D1.push("Got anything to say?");
      DialogueChoicesP5D2 = [];
        DialogueChoicesP5D2.push("*Do Nothing*");
        DialogueChoicesP5D2.push("You ever Going to say anything?");
      DialogueChoicesP5D3 = [];
        DialogueChoicesP5D3.push("*Do Nothing*");
        DialogueChoicesP5D3.push("You ever Going to say anything?");
      DialoguePerson5.push(DialogueChoicesP5D1);
      DialoguePerson5.push(DialogueChoicesP5D2);
      DialoguePerson5.push(DialogueChoicesP5D3);
    DialoguePerson6 = [];
      DialogueChoicesP6D1 = [];
        DialogueChoicesP6D1.push("What else does it say?");
        DialogueChoicesP6D1.push("Is that everything?");
      DialogueChoicesP6D2 = [];
        DialogueChoicesP6D2.push("Dave said is wasn\'t Chloroform,");
        DialogueChoicesP6D2.push("You\'re Hiding Something.");
      DialogueChoicesP6D3 = [];
        DialogueChoicesP6D3.push("Are you worried?");
        DialogueChoicesP6D3.push("You\'re Hiding Something,");
      DialoguePerson6.push(DialogueChoicesP6D1);
      DialoguePerson6.push(DialogueChoicesP6D2);
      DialoguePerson6.push(DialogueChoicesP6D3);
      DialogueChoices.push(DialoguePerson1);
      DialogueChoices.push(DialoguePerson2);
      DialogueChoices.push(DialoguePerson3);
      DialogueChoices.push(DialoguePerson4);
      DialogueChoices.push(DialoguePerson5);
      DialogueChoices.push(DialoguePerson6);
  
  
